# Installe les manifests de MetalLB dans le cluster Kubernetes.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  sources:
    # Installe MetalLB depuis le repo officiel.
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.16.1
    - repoURL: https://github.com/Commission-Web-FPMs/k8s-cluster.git
      targetRevision: main
      path: manifests/metallb
      directory:
        include: 'config-application.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true