apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    # Important, pour appliquer la config Après l'installation de MetalLB, sinon l'application échouera.
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://github.com/Commission-Web-FPMs/k8s-cluster.git
    targetRevision: main
    path: manifests/metallb/config

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true