apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: carte-fede-main
  namespace: comweb-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: comweb-db
  name: carte_fede_main
  login: true
  superuser: false
  createdb: false
  createrole: false
  replication: false
  bypassrls: false
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: carte-fede-main-db-credentials
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: carte-fede-main
  namespace: comweb-db
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  cluster:
    name: comweb-db
  name: carte_fede_main
  owner: carte_fede_main
  databaseReclaimPolicy: retain
