---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carte-fede-main-db-credentials
  namespace: comweb-db
spec:
  encryptedData:
    password: AgDAmRrLj2Nz3RMQnXQWn2MIpoSt2z8GOMfeU7cbuWPWWXlQRJ9ZRGs9vIgagnvvwX1yQUXDGw/iHR9vPQYlEu+JNN0DU/SLQ0WTudjE02fdkAyoKyAjDk3KBmfjILPlCHTPoTDyHlxHBY/VwEKaXKGI1eJoJW4tNPxA5iTQlytVzIcoqcX+E0vZX2N8Iv9erVQDg5gtwTpY0qfAw6/YhXQfB/EUfi2Gi3cfg2GXoCEmQ4blREPrV+YKE7sG4M0ipG7wmZorp6PO/bcOYgrhO/a02L8Et1EvkJO4EjpDvg3TKCXZf65Nfu9v87/iYH4wSdSNYwkWYO6N3QBsF2gKHABR2GGwprCi2U8rsrLnyCX5PA98HA80z1n7eASROxRDd6totuQyuvl4qwI+3fz30Q3e2Ec2QP2khOtchUQ2XSbhyYaDu+xmAljAqsSIpTxgnmX2lvrc23CYomKRqbER1cnnuxdcu6vRYy3iUUWJ8Qfyac4FE7EHAzyt2fWLkydplnSkxe2q5zCEQ1lD6mjqEEej+yRXcqqIE/1zokkyjQmoKNPTueN+q9BuD27INWZMMpYz8xEFJpIoNA+OgF7L13tc+J7oRrlVenOc4cMkDGpPpi+/B8Kvzk10i9e98loisbMi6VXJe56z8Hpd/2eB/v9JTiKEpsK4/CAgQnQ3J9z3+JsacD8w1yHzcznOwXNCpfguBMBeqRa/Yom053lG6/R2Jdq1q61dbjx62qL8NMR2v+bD3NnKqqMC6Gz8GwW6LYIfrB4Gc5pSHKZnQICv5xoHsT//wFSqmmnhsFoL2/y1SgBTtVky18/iUYIX6zwRyT8=
    username: AgC/eP4VlDBn6ufU0aQQNpazWcVJ/7Qx8G9t+FNPjnh1ccKBKnCFcpJsd//9k7ZNz8ELDHzIe2S3WBzJAxr6shF1OCzE5PvMrRc4GTjOQclTSSzNcULKM0K/rItTkp3APXjVLUAnzzHEncVdzhUL0mpQXy+A7zhRgGupgISMeFcPPXkKiizB09zc7eb7oZt1/qwGZRpCi8E56nc007ShAx43i/4mEdhfkEq3UugG757AFNqJo2+l8nXBQ7zooETtG61vJ+ucZQJughxp1bFfJgmMYM7Gm/4DlrDps2HnVzlQ8cucbIuqJkaHQIpUcHSy4oobcogvKYOEosJUZR9j1pNIdTc/4hZ45f+9oCxeOhnMIqkD9nq6SR9qPXlUrw7DiQU3gkovNDvZhcgHg3Jefw1h8z0Vjk6prUJUtsAOGhgxQOLZzN2nvYxHBw01V8DpWorN7mHuZHXO+SvjdRvZ3XZbtv6Jyvw+KWeqDRfmpkuF3JT648S6Rv1YmGD0lm5iGViBibVD0hNY10OPL/MwpgCTXPTtszfrt2XiJ0+lNMGgYDW+meB+O5EoL6U3bzZGwrYruXjkL3GECDnNRv4uYwUFksstGAXGkMzrM2pUemN5i+6GwDseJ9S68UNrE55Jmk9olEWBlcMrttmUuln69k38hqrW6amwkB4BcoFjmz/skyFGh1fmNAxO6mjOdm1bsOSq00+P+pxazdP+Cc3wZM4=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: carte-fede-main-db-credentials
      namespace: comweb-db
    type: kubernetes.io/basic-auth

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: carte-fede-main
spec:
  encryptedData:
    DATABASE_URL: AgCrGVViV3M+TYWCBrYCNRAnqEeAbuiqrS1uu6A7jHvwblknOVCX4qY4yfgTZBraM7zVzxzgF0LuQocV6ByNlUGtYVYjmYPmZne9KOAfJWIsXWprheN/MKO0QJyTiG/guAv4bLjh4HUdZPuTiG9FgvHHflyQQQC7Eks5PEuOUToPLDAalYJJTJ1itls/JdbNv8k0C/00rSeU4wSIOeIdKY+kWxZBOnJs/46hkVxi6DRR9mqUi+3xuqBmiflwzLzLfIj9FPe9G1Ar8GfBuRiwssQoaJWKNEZRXwAAesO62Vl251qBn6SPCzYh9hljgfyC7mOr+j7JqD9P5EckZ4F2jY1uaNeIE+GWwVmwtyxg/LK01QhEXiKMq2q2wvvjz8jZQH/w5mOlrJEOQ6fAZxMd18R99ZOuzXu2DLdEawfUvMK1X0zrHJMbOccBX4OB0TE0ML0Fg2PNmkY5uDj722v3FZ0vWt6yL9Hq7hUTnqfcP2aSMXBiuuNapX2yQ2tlnaL5/tp8e4T31W0Q46y0kyCisb3L/b26ZCHdO8WhPotS1X4zD0R619yJ3rVqRyIvt++k0azR91l+qvwJ4USzZA3u7H9rDh1JSOoHCKFe00OpPUXax/A4dEwShRmUu6cfLHQsIrFmSjpCArSXmpDVYpKhVHMPYI3sDNBhM1T40OaNanVLLMDL0lIOonR0tn36w5BWM3rIxxgfwWXwEqsB9P5iv9A1G8DqpBhJ62H+tVkr4P2zYpppFZIQ7WK2H1rsrVqDJMgSRx3WFuOpzZxU8GmuueXAteptc7xPoxrrYHKSFfs5H4gnqha1QSic3QCdMB0fqerQw7Y8i8wEruK8I3aNxiMC7QcQs3YPmBBO1C48dWbIDKKhMlMyFaN5GKWkWytc7T61t8sAzWOwukIK6Kba6YyNf3yyButh2N5se/8gCeNPa2iVHGaw25hB20iPwvYVFgVMYLA+xkyCuC9J+k9PJqA2AkUB
  template:
    metadata:
      name: postgresql-credentials
      namespace: carte-fede-main
