apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-credentials
  namespace: comweb-db
spec:
  encryptedData:
    username: AgBXkDweJYIhnfZnMFQ2XeBnJiP599UmwY7jY2Yh43lL0VUWqcTRsEYFJ8nRh+e4Oy9uAqszGQgLIh5pa4XmE5/ZfoHXhOAKFwfhBog9mCfJZNOLqLWnlxcC+IPk7/J1jHow2fmr2F38hzUeDKhdB994SNPR2WBwuK5K74J6IhmH26c+eSnvjBTY7VJrj22hd17F7nGT98JD9+zX96bMbG9TtA4gTk5VnD30NBEH1btNOs5aTD1S57jOHtZdZb91ic7JTzaS5sI9WBnyxVyEDc0FJpNjl/Sb9ruWQxhNMYQ5OCuaEbJ09WxkZk1E9XCvDdwnufMNMuo7k7HAK9sptAAywNd/oNaEkUnSluHPahA1DHEYcubXOD7SeWpXQDjBCcvmnIzk/bqMg6s5Hw4LnyS4hjFiGA0+cJ3lG1kCggapahyx/ST2bR480/KsoelWcHpQOADgp3MNKEuBQ6LJmbqnYqfR8ibNib2n8/5J4LLlYSuDeNWAMl+1wbpWaiUYBUpQGpELm4yE5cdtaCF+eCBt4aGVw4rfFFJAq1VfH+ZNPx3Knuw1yRMN2woJchzkfsAQkf2RzMubyg9rIv4VUA+nQlIVL2RDjzeR8FMNhbOKuW+rW8xyUXLf1TF17k40VWeaoP5xHfu4PHJQfFmTVS9cjnK3hXqx7OOnR+3m2ixx+1fTrQa7J1lqn0G/toonCvMuQcgxpe5SFds=
    password: AgCK9Dy1AQ/lDLANZuOuyUzWAmWqnb/su/8woNR5yzGG/4bzPL2XHLdwKOpWkgoaBuDLmBxhAtnORBPvciWmHoBVuAclRGutoiiyu0qkuKd4zoQYMHykS6re+w4k4F0ZukTdYs+x/OzUbGXkroHgf4WCHgeQ9px0e8sxlwX7swdMwHDR8R+WtBOq3uVi64YxaaJYskAoPFh6z6gyLjuc5LGqHC7Md9Gtzw4dMLlrc2veJFobomlebQLZXNF7jupRLNm2b3DSX8QQZID/bG2BphwYFT1KZ0pDAUgA1gyOV5hYWU4HZx3ZnoG7h4wgnLOe64dZH7QIFgK/6EsP0+8qSm8HtDTN4ojMNc/1XioHTadZQyAob3pSQ3HEpz5zR/fYSqL/BmLDif5HJG87Q1B7yo1J9RnWUvxs7JBG0yBbN9AS4IH+DVf9dSeAdQL1UioiXlyuYepKC4QaqcHSNwWhwlIdv4Ty4rPKYKtypS9GEU7tEDoOWr+IQQbM0CmvDCKkFFw1SceHgZJ3EhjZEia44ZAXUSAXBU4gTtLa5ZWEUfGKd0N+Ugcc6RnCCaw+JMzbGitCA4A1ZkT282qSleMUhXCGePPEeNnryL0UDOTH/cba6wlkkHvY7ncJ32FCc2HXJZwPF0nx48wJzkCZW/qMwBpoL9L5Wps5ZHmCJXxwIRl9qo3wZCV2IBFD8j1QFYc0+wa2j/0apZxBr409PTH8HJV83LnQ49E7EsZ8SwFeK3ePuy9cTtgm8xdMjDgNGEW526grFcp3MNSSE4zbot4oSNi9
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: authentik-db-credentials
      namespace: comweb-db
    type: kubernetes.io/basic-auth
