---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgC5Qhe03wkAK62mIDxoqTALN3iip2ChcP4BgoCTRZ6Fv26stRD22En/sQ3+qe/zFPtFcknSU31OwlkvHNwztl0rDde/R/WMIsu1nflPDEBCXxOAA55735e1ANIjcOeLGgu/0EQcy6uEr3yLWTNbLrrUOMjkb9h4qljZYgW+6ifFb2Nc0vyazC9bHRyE1PkORX8Wcb6WMbA7Feo2fhCALNNFKKji5hSdhdt1ZDNmCxy9dWJJbVvaRZwVnzTirDnBoZsmbuw1L2AtJFtEudDOmFGywtS6puibA+7nyhPuI8C67f/9RLaNSwkUWnOtjyAgd6yoyRgiwPBsfnNcErpi1Lt7uOwHwotL5eY/lC4ZAjhp93ZDZu0zMpegfUXVcYQGh7K36bCdpDhgFR00evBbid8KSJLz4gI5tADNUV0cgDiGpKCEHULIoNO9vuBFyLM6/lPElvC6bQWa0fg1kpmYS/zvB8Pu7mGFcxSpIC0fCiipeoULumcMfF63rQ2K/PHNbp5kYyj/U1uFX/cgq4VecsyZRLDLBsC5rxduRzYvpXFVFKLegXgBJYBRrSaU2xa5zUDz0oCCpt5lHhI2X7dgYRz9W7g+cL0ZWNpZqRQW6rFoEKzdmofBDcjizq5LXPYOXjJYx2gXvgQaJXT4xNEJy+gurrCa8W2nxyMxIQq4Qrv2tVfN4b1STFp234sZfxXB2sMc+cx2J/sQuAB28BtzucZeR6535N9A/WDCLNsS4T9gYqmHRGmshaWE9SIQB9kdTPMJ7Q+3n0flORMsfieyHmU3
    AUTHENTIK_SECRET_KEY: AgBtvqhRXfjhBHCR2x5aM01Ew+SLlFSOWzZb/IrGUSMv54A2SoDeyiHyCL6cZZV4QpN+KH2xiIqALlt1btEIDq5CRzXevB25REZrTH0pJ0eCf+cllUDZ5xyR88gN+VfIDGaGN3E+9x1kPJryTkR7UpaDmEZ8ivtOgo3QK8eAm9GoBv3T7O9yEBCox54or4R6ovj/jeasmSyJ2RBBJp0hPVEOCGGftiZd+gr+Hs+jSshwmVky8qmhiV2AcJrvUr40e7CfS6cT0MhYHghTeaPVS5guN1cO++I3OA1npAJHEc3CXxq2StaLOsoho0iZourimf2EPwDtX9XRm1C/HSvmc+i19d0LuBLBp91CvJB0ogQcTO5P250DYb8oRuJXYjw5aKfcTIYS9YLIfPNx6iTuwYWAkwFLDQvuIJl1HyX5w6DtomoQSO4YQuX+vjsgte4aB4l6zw4OIwZVlPrONMlAIHtmFT05o4vC26kUNll6oxjrWviayTgVD1SyS52Rftt+GXd0S8qe5Uq3QDNpCC0ZrC32VsqvYKhGlberV/aHO/5QtEwu294zjAo6psU0nf5kcGKPnUqY7Na144FKLIztdSN71KWyvgE+ls1NEorjnFQ6zkpvDjKBecBYCPfbSHhbg5NJyT6LvaDR7NRAnDcKolBikNbW0TNxAL8HfiK1+ORt8FUJnyeWdDfMBxy6/gXegGaI+b5pxM/3VOMhUJEabLckkbfP2QLBC00lGvNZWFcvGobhfdEeIj3J1L+dfc+rcGWKKIkc2EpSKR/en0MZOgrDfTPUi6xfHmSbpGVpiT93Iw==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: authentik-secret
      namespace: authentik
    type: Opaque
