---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-credentials
  namespace: comweb-db
spec:
  encryptedData:
    password: AgDBIrfQM3AeLERSPCMhhLOCScE7GympvvqgjHjlbUNoxQBJaUool/tGBo0ay2seGTp3ySzsLxvrCS2lafDunZfxkmkyXxoL20fmI29hA7m4yNB8Jmhq9CEr6TU26rcIYqDMo4VBZlaR936IqAJ2gVc3PbBS6BPABxSjH6UjB8FTY+NIc+UGcAHFAI67FHkdk1Ag2M6Aqj5LAo8Gpkwk9D1GRml65pRp1lESfXXSUFIxfh7ijmN0SmIgD0s1DkX0oZZvChxoRa/2m289qAbmQXawk3sN+Y2/q6MN/8VTwqYlIWpnDs5uEccfMlETfdzYabpUhhYT3cf2scloNmej+HeZWVDCIagbGK3gtL0TufoDEfdenc5gdZRcBV/NdHBFJfEo+RDVDBMs7xTVlXClNxrNc3uzN/aUZzpxNLqOr7ATRHaZxxvvKpqcrTM8+RfEJOrihRZyKK2HxsUDzhMxgTeW4e5Yb6J/00LG4f9PRZqIryhOV/DJX9PYZEV7Y8zqU0105L5GVadc29LbB/ToOA3Bb0KE9wr060sSSKzIOHLrrCHRYlyot5uEU9/J/cdfEfYxJKTXkbONuSkAXbjwVtQ2DX1ePWhi+CI4Z0FLMxHHDP0OlqSFw4iFjBqVovD9A06nuSDvyVrSw5hfPsPtXvR73LTDnPMJze3p5K8skRSlR54dI+45kv43wShFdxOFqXe2xtqOQ67Ql6kTIfLgu3a+1a9JGQ8ppaF1Z8aV5xGyOSdeFiiCO2vzabZhV5aZvRXCYPYZAwClXtFH04l9Qjcj
    username: AgBTXSQi8H4zl96sj0ZvtoJRKj5M9Zs8N8HZD6VLPOj0NKziugG+7IhVbWqyS5kS99oWzH1LfZPoxAVQZ7q+TKibfXCubwg6MJdYFswPnHZNteAdf09jFCKV6AkLn2aXWsIBGY2dHQZScffotSPaR6srthBMl3xkuWuhsphbBgzf/aP9ZjjATHKCwLfCZhOBmE9crzB+ZVJs8dI5wDg4T1LOi3jBoz5U6vEx+PxP3JZt0hrARxsfzurlzaEJ4Al6YdyrQF11YoEwhcHWKyeTppxeVwmt+7UTVmz5WvLYuTI83y3x+qoOJlcTFxdEvmd8LUU2NMF7pW/JT5fyAK3j+KAFOA/16KJA9YDboAOU9bTvh8t0hdxFSzSGrQtGchdXo2lUjpGS/FSHPOP3YSVDwhcDiGp8nxFe6hMKJsPXEdaimSIKk1LMVNkhvsi+FNcSp9QDlY4QT8GjcnwHDG1TnpO1CTTc70en6svzXMBtR9Yj17DPVK7c0KXbV970mSVKuOEgRIH/SERSaaf/BBM4Saqs/LrPtzUCnxcfVsar6VnAZ5b9UEyRl6vPNJffUjYuffCiNdB/CYXMGkCWuj7B1dnaWB4qoPSHcvILymXZICTdUkV27uIphrXoBhPe+gs8xQiRo7jD4fOmMd1u6d0hTx1EgzqxyVSszkzIHgtrSGBk4HbztVK1ZzjEgCvgbKXQ+u8V0Gtfw+gTqDM=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: authentik-db-credentials
      namespace: comweb-db
    type: kubernetes.io/basic-auth
