---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgAHMGzEhB8qnyOhRZRL4PobKdF0ju29rzxcAuaD6/3Hcy63l1Kh9Df3h0PmGbwvqmU9+sGjRjkalPZs6C2VloRbNnKRW99GBytyFHagRezghZv4kCqD82BH1lVROuUZKrTEgaBl4HTNc+T7ZBy07NZo1Abab31L+ReV+CulWI3OcSshjcBKTU6f78fNjx+UHhEAeAFaNA4FCVGZNjijvo6aUZzAoSqae3QtNG723t4Hjwe/KSft3HDtqcRWHJE4R+B+DpCNn13Qh9xeFKSUu7ZSo/Y/usyp1gun4hD7xyCxG6YTflHmrDZS/A/WI7MaPfZlZFSf62eS8XjE73JUTrta7akfjvGXSZ5tpoDVXWyyxLUDIlJu+2/oyr4J88Tnkovskzbb+ExLRd0rHiB0S78G9qgYajeUSJM8MBJPpD4I7AhckAVYQXaTiD+7+6JqN7SlwOCgRujs+flR2Am/EtumRKBqjoTcjlgYJxtCvEumCPsF2nK64GONrJAnm0iJJjPSCMVSlzodC9J/Apz0y+IahXrZKa9d+lczTA54p8Ip6KGw10ir83dedUxyNDGmA2UMM86fW6ULcNKAsuTJ8UCbFErE4Q821rDhUMFNb+IAPP0LRllOX/0HpQgOaYWL3wfbJdsLfEgIlwETF04+6a3iv0p2g9BMoB9Nbi02RZ+vkYZx6GY6SzOD8wAaKzMpoWojtW+MRRC4ahNpv0mmCYw43+NbjxBpccWERxLOYp2BRhu30OwI80OpN4qqRSIClKRoY42R+asIWICpgwmq3u+IS3WP5OBiA5QFKieMhLWO6g==
    AUTHENTIK_POSTGRESQL__PASSWORD: AgCdnVuy6hx+s6FwYDK4suPv7xU6n0/aMFcnIIC5w3Pwe272xNEPByZzAa3Y45adBHuPJlzVzq8Hw2/JzVNXb13dvgPugsrzXsWWm1hfK8fjP32V3VdPyfmSfKxhJ9YoexuM3HZRT/iSomPAdhsKzqFrHFsjZqVdKtLdsDtyE4SugQbZuLQhKNW5qd36ZbJzrB8L5oo+d5KcR4q/Xa/dS4M5aWy/mguLO8jPcCbm5eiolAVSA0/sfXa5yUVkL0hjFA7dwKLfwTLaWU3rzFJaVO7XwIOt6yWYF1XOgPuZ0nkkCo1z6AtO+vHXK4HW6vcWymETHvbfKrjBekyJO76h8ZPQ/Y8VPGYil5PoFT78U6hnmjJXZGy0M4wRNqMpULOkKNW0xCpeNOM0GEDLzbW1/1GCopcp84XM744EpzG1ljB1Za0lsWf24Ak60BNVYfVHyhbJuvdbcP4Wqm32r2IXHcUPdOSbkAYWi6IBGKtiWvRgutLTSilksrOnaxQOf4nQhhrlpCFIvYA7z2DQn3MicPwwqlhQhfiqD6BikZ0xasd2RLDffwwEs+f6bLDjJKUsrkIGRDkoAqUaIj4sxzT2znN75PPjteP8/B6bzCyWBWFELFkKDMaytimcvJljv9AXbsmspvJz9cjAqVt14JYYUSLs/Xii33yCu0+TdwPz61EBQueF7LJfjoZIr77UfR7002ahIyzB6azTrZgoKLSn46+E0KInX8czzi/8Ptvp1KXyXWyGC+RvfCbngX2YY6Dc3YbhnrJVdfHC5cdmkPYL70Tz
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: authentik-secret
      namespace: authentik
