apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: authentik
  namespace: comweb-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: comweb-db

  name: authentik
  login: true

  passwordSecret:
    name: authentik-db-credentials
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: comweb-db
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  cluster:
    name: comweb-db

  name: authentik
  owner: authentik
