apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - migration-api-credentials.sealed.yaml
  - authentik-secret.sealed.yaml
  - authentik-bootstrap.sealed.yaml
  - authentik-db-credentials.sealed.yaml
  - database.yaml
  - application.yaml
  - http-route.yaml
  - carte-fede-credentials.sealed.yaml
  - integrations/carte-fede-main/worker
  - provisioning-job.yaml

configMapGenerator:
  - name: authentik-scrypt-settings
    namespace: authentik
    files:
      - hashers.py=scrypt/hashers.py
      - user_settings.py=scrypt/user_settings.py
  - name: authentik-blueprints
    namespace: authentik
    files:
      - fede.yaml=blueprints/fede.yaml
      - carte-fede-migration.yaml=blueprints/carte-fede-migration.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      group: bitnami.com
      kind: SealedSecret
    patch: |
      apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        name: ignore
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: postgresql.cnpg.io
    patch: |
      apiVersion: postgresql.cnpg.io/v1
      kind: ignore
      metadata:
        name: ignore
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
