---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carte-fede-migration-api
  namespace: authentik
spec:
  encryptedData:
    API_TOKEN: AgDAZS/n6FqKLt+tQw9sr0KzjIMaGdvzf5/bg7L21j6XQJGw4c6Q+082QUzOUG6Y5C90NDXauoHxxquSWB9gYzyH7GmgLgx2P4ane2NAPaKqhF7JxrGlNvmMHi6HU61YwS0GhX4Vgvi6615/MuP8A5nTlxb6gIb9/1u9ZsHIJu6al8KyYjFq2oToHOnsvByymc1/Ito652QcLshUrYkkGo9sTieQUMBV62K2y6h1RfZFDB/dbRt5vcei3J69tHcN+nX0erEh1HWuk/m/vlGeIkKxEtRr8tq7bC5/8JEX7a+/bntgEk4tDQK7uc1dh7JYO1WTNLVpiCr7JXeAHyhwTpCaQw5VloOdT89ptqGgY20+lfTr27J7hNgnZSQksscC09gqAcyPUGHUmNiceBJy9JHu08VXhVsp56EnoOa4fITGAygOwzMwXcvJTVTohj6Xbvpql2dH8EBXUzHrqXh2p2H/l4q6S8FXmvmzAnxuSez6hJrroRexSV1BY/nHxp119D+Oa/tVIQ3YnSW6GKgz0K7THd0NeoKUhNXz8G/maSgIdBIFlZ4CCJ3T4nbeYjxa+NHHM5ibYrN8sXnLamIikOPtwGrvnDCdAyFddVZENpgRHFDOgfqO4FbwfIs1Wl0kTklYkDvv6EbMMs3qOLRbs+LyHVeOo3LenbbABy9nFdgsEf6X+LPwlsojXz0THLhyzDC+p2o+M6Bfl3wcZUaliKFCK8DK73IvlSt0m8kU2XBW9t0e3GitLdlO9u8Zp+P/+h55LU99NwDd4QCZHPL6CTbv
  template:
    metadata:
      name: carte-fede-migration-api
      namespace: authentik
    type: Opaque
