---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carte-fede-copilot-rajouter-envfrom-values-yml-db-credentials
  namespace: comweb-db
spec:
  encryptedData:
    password: AgCxfeQwMbgVlXEgcKsrndVyJnOPWbY1eD10xsmBowF/QBkP1i1422V3WDAWky8dIeIgUgSPHs+4PwTsMDSGISWTWAk2lgX9mjJXr/XulDaljBV7wu/gv8YbOMomE+A7ptHP7u2iHPsjEILejkvDw11Txtx/HIvt2W/0nrbEtlT+DGHmvLo97dWmXJaYq19FAwC+fYbW4YKN73p7paeSKJtXj+ZOZGQdiPqcsNMQJWs975KgiVGuvcStlPQWBdUTnV1e0pw++yPUS3ejCQBddYISwiGtusYid/1oirzcKTf4ztS/uLFMRzoggmJqHKmdopAVYb8iDxtuSsxd8/fFhYMfvElNcQmkT6JBSA+bLe839ZOu89x9P6E1BsvZ0f8zQZNS5rRdFOy5+bf5o3L1ixav4QaizTvxiFTWUuprYI1AD6er/PNB85tp4NJmlBY8jAbgeV+0Zp9twxrChnbVvQdBpNRedSOAkcEw4p3Qh7axdM0hMrVcKSbdsxgDnCELFNLmohdI+7AueoZMccKR9E6PPtEUNSX121LmxWcH12joCs0QIVtxn2PbLYGtzshURbWazIUQ6JUXiiY7Vkgjo1xwPcmgA6a9+G8XrDzb2iSGLP29Lm7If3aahP17lcsd3/ByiLOBBEznfffW1u27BzcYKldZDAVOtO74Z6nA8RNV0RBNcGorolBNO1bCP33p9ocfVerSl/bSyTK4oyvRkVBCFx/tvNJGkIg1aEw1Ex9H0YR7CQ8sgeCeKyvImmG7AJ6NK2PZPZMX/OPQzKWmIeWuVDIoD67f62HmaRZsvNUm49WhbaJIvEEUoMRmKjUHn6Q=
    username: AgBj9t8HgU8yQlW0NY9BHLQ1Di/+H6EKhLrQ9xXpcUGrQR1rf4TN3kZlQcg25mLMkNKGymZxtZWOXk9ckwISosPBT+RPQG86jwA4wSXhu79MyiEVjZCykXv/mTOXFgbGaVEFh7x3NRD6jcZsRe40Ua9ivKf5gf5wQITeOwrvWDDSxRycxWM1lj1DOlnsv5ppSXKmgEHbn9ePlSMv0PtIje/gVh/qsY/y01KNsocZeKfHav0H2HJ+z/s8P2yDAFsVtwZfrkGpeKDibR1zMZnoYpBot2GNAIRnLaX/CF5DtzjwX85smrXhhvebzT17iPpWP8GIHQ/PBk3GCmjHE6mK6wHi88bG3X37XaHivOI8drZw9rWev74Ipv+g8ueJEeYrFEBc0aSDltNynSi+3qqN5TfgGUclhwO7bxMegP0ZZ2YxGunJcWl4OpxdctCNTe//iBdoGcYjJHiRkR2qXIWNPJKgJ9eQlaMpVyIgBvetJHZpRGfxmhSBnBdwMPeEEnjMyIsXm+o/cQHBn2HWgntK/9nsEKrIGmssGAuRWujkVA51wq4SF1xeZCS/8bHYr/R5M407Fy4p8T87pPzIXsR8MWaI+0leSEAMLPtuhAmVLJJeOHMcauqqTRcPlWKMKoH+GW2EPJGZvK9sI/K3gFqkp1k5xEVpeJmyIoFMcthxMGGrweq0TNAbwc9Sxggz+tI5Y2cUizAYSd4JELhf17X7xygMmb3z/lo6u7/cElz0gOXFas5TECnSfNgUm9ZMfVYT
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: carte-fede-copilot-rajouter-envfrom-values-yml-db-credentials
      namespace: comweb-db
    type: kubernetes.io/basic-auth

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: carte-fede-copilot-rajouter-envfrom-values-yml
spec:
  encryptedData:
    DATABASE_URL: AgCLkqJTTX4FsYpZl4YveG04l/LBdDFkS/szRwsN9Gdw56/0U4Jjg41MucmZqZAoWgydhsRbX4Q7DRvp7I0Z18464rUfQ9UPs0suLbcpSF1UXBqflWMbU4Nfp3qk+91z74jhMhQJNJnacJlKokK8juwyycd6wGCTC5ATmQ77F6mlVRleswI3AaKrWoO39lIBXneknm/eAXD5Kuen/4QOSEDgNs8xoyY1sNNvq/7XvdcxybjI64qZNrDqOsfOSBpm/OTbklnKo/Gn0nrVVWGQ9FaLuMWhh3vGRg3wr7YVYgwrbQVma34l+SdJzZXGBhPuddKr7I5YQzt2+3tq4CR8qUHj7OV5W8w/N+w391x7STKi8cbL99wkn8l/3/OMXqJyXA/LI4OTK8wE9fJH9/y5PMgXZof61Z04on2PwwNqdZ9kiZE1XYD82nluBLdwkZIdj45IAgQtrwAOmexDB3UIKj6y6AO+5wy7KPWGvQo2JCMNdev2zLraQT3oKOlqgxFHFvpieDslaTrM7vHZ2kZmybquPTsSRypzjYsk56mPcBO1orih1qwh1zF2GTJncL+vA54tF9W1Y4lds57HkbVDydX//yktiNOm7mfKwBSwvizwZ98AFhaFA8lO2+GIA9aj44AiO1ieFMM21DtD3eRYqXbdv8k/9NnwF4jqMnSMSar0g47uoZ7DcNlcR8yDkVMWeYjWvMoA8+j5aI3rJte1m/R1nYkPk1fy6icIfg/IbZ8bxZsiLw6bxWFoEVxxvr/hOhpPV5JFce5pTMpz7/tvmJvB2sUOBLL8ajCS30yla1yB7k0Fb96Vp650QGN36oT+uVZcfgpqM8yd0FGQcvFnMR/my4fdtVMSyVr7ETphbQKERdgcla5fYYEzTIcbWWC4FCDPDq8W2xTCjiw0buX1kQXOysvX6iuG+kVvuMMd0vozynOOEjC2IHmMrdKzSLVLDGNmsoMfFjiToZa4n9VzdsjYk1jdfYLttV8fgyA4V9NEoF7ghsedYSuRhsTY8DxDhewdmMj0oRaRa/FyK0x5oDFEh8tSXbFLeEdetDuhwkDXxGg=
  template:
    metadata:
      name: postgresql-credentials
      namespace: carte-fede-copilot-rajouter-envfrom-values-yml
