apiVersion: helm.k0sproject.io/v1beta1
kind: Chart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chartName: argo/argo-cd
  releaseName: argocd
  # Version fixée de argocd, peut-être mis à jour si nécessaire
  version:  10.8.0
  namespace: argocd

  repository:
    url: https://argoproj.github.io/argo-helm

  # Ici le repo Github est installé en tant qu'application
  # Puisque ce chart.yaml est déjà dans le dossier manifests/
  # Il sera lui même géré par ArgoCD, par la suite
  # On obtient donc un "self-managed" ArgoCD, qui se met à jour lui-même
  values: |
    extraObjects:
      - apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: root
          namespace: argocd
        spec:
          project: default

          source:
            # Cette URL doit être modifiée si le repo est fork
            repoURL: https://github.com/Commission-Web-FPMs/k8s-cluster.git
            targetRevision: main
            path: manifests
            directory:
              recurse: true

          destination:
            server: https://kubernetes.default.svc
            namespace: default

          syncPolicy:
            automated:
              prune: true
              selfHeal: true
              
            syncOptions:
              - ServerSideApply=true