# Cette ressource décrit les plages d'adresses IP qui doivent être
# annoncée par MetalLB en mode L2 (mode ARP).
# Chaque noeud devient responsable d'une IP de la plage, et répond aux requêtes ARP pour cette IP.
# Si un noeud tombe en panne, un autre noeud prend le relais et répond aux requêtes ARP pour cette IP.

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default