apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: traefik
spec:
  gatewayClassName: traefik

  listeners:
    - name: http
      protocol: HTTP
      port: 8000 # redirigé vers 80 par le service Traefik
      allowedRoutes:
        namespaces:
          from: All
