apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Traefik, vu par l'application racine.

resources:
  - application.yaml
  - gatewayclass.yaml
  - gateway.yaml

patches:
  - target:
      group: gateway.networking.k8s.io
      kind: GatewayClass
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "1"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

  - target:
      group: gateway.networking.k8s.io
      kind: Gateway
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "2"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
