---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carte-fede-codex-frontend-backend-http-routes-db-credentials
  namespace: comweb-db
spec:
  encryptedData:
    password: AgDFqGp/6PQ4oaKdz9uAKpD3TJ7oBvNSEE2BlD7W65uZk85HpQe9UQ9bYryO/4UistuRlU9vMdg+CrMShbOJpNv7xpvFYJ6aI4YYVzwOLI3lZ1PX/j90Ca/TqBWmBi4Wox6dXhN5VRBVNBLnC1ZyiE9Dy2yAHWbCIVPBgjSiOIiLinO5tDz7q0eDETJFKPqVgK9WpE7UuAeBPBU2HxMOUAeq+WvaBh5Z3c6bh3dO/Naz4zJS45B0JBH1VZ+nLebO3wcKxXocZ0CTQVw43z9+HYRyZvWbZZd65wXyiHsWDiD5cBnjNpLlsLFgSYvTL+FsZJuXu9o8LWgQkDlMB95UMq07k2If8upGxS93sMWQeauoE5ChexU8BOkrkaMs/dkb5c+UJr44g6gEP4CkeOnKMOv2mmYC+t6onCuigMoIlbGxgrYyviqBSx6D9GXvuQUTPz39C4n5n9Kud02IKT3aY27usSOYerZwl4tQX7MzjtTgBzbR92dCpo99yhfi0kUy89ULalizwe9zmKo+l9DyHt6hhVnjbamdziia2B8clgY/Sh25vuB+zdtdJ4GlGdqCWilcAvy/aDJPkxScrXTiUoMVQzCej9Xytqc1DXLpr84J3RRZrfBswfJKGiGey7XUQFOubIvCqvUT5ZIQiizdBpOxECZcsCPYhGCO6El3d5Q458ZfTqjKig+OyBZisnCTGCcis9KYt5wb06dz3wFGXDapFfcoUQ4iwDfC4S00fMiH/APzQONN/scLE1a7tUVAOfYJYnRC25lywN/i3wt42fVWg1y2JSIcA7p2PE394Ybr5B3v0thxjxpuVYvSTvk6Zsk=
    username: AgBe785FHziaplBaIsjHzkGqzTPi3+KQFGz23tHO7wRSYKhUHKOqaMunBRsc521xnRHip5ktHOplh37cGrw9vgwkLCyZX2DPTZsWY5XgvKBr8HrfSK24wZ70RvA6DdkJ8lcysU26GpoB6YH+4AnYo7OH+9gWnWEqHMkxkh4COxCjbWou6S3ZO2NCDlZ4NQNFgXWak9gtrJWtQn+b93J2PQPvoKtq+O487z57FtONbeB5RUpC65OYpyNMVzzi0XYVumOqyLDJ6a3kvHhQdi746G9/EfSCFTA9Ro1DSzJP1EeWsKjJX9o/Z23g4JpNyKpLGHHjVFUOMcniA1klFKPJ0XQBsK8G8/evOr3xlXIDurr+vT9Csx5m5QjnXZb0M8UocheMO1kTCmPsJ8qtXaCVxqzKjaG4GEXEaF63iTtuqNOuVdFRaB2WFXgd2MK60FOvDt9hr4T63WYjg3pU1kotqI5mUBAp1durmra0KIct4Rl6WNRScxn2UGGU7tQFeaguKfONBa3ty104bJk4I8FPnvJoOed2QRj2A3oznKy7S3NM0CQOHYw5eSCKmSr6edpVILPtddR2vJF+vxEANmEo78PWNkFlGYOo/sa1jU2iAtn/caomFDL2ROfYNRx/w5J79eEBYEszZdnKS6kmPC3LjjsiM35yZt15KJt8rEM4K4dWbMuaV9qdNabV68WCFzuqEpnhjj7AMf/zaMa8kIBzrtvZlkIYq1FvktxaVg5DAE1fsXsfHPHjj2qZ0SxQ7pc=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: carte-fede-codex-frontend-backend-http-routes-db-credentials
      namespace: comweb-db
    type: kubernetes.io/basic-auth

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: carte-fede-codex-frontend-backend-http-routes
spec:
  encryptedData:
    DATABASE_URL: AgAFQBAoEKbGkjOgyld4dcSVMavIXKqnTkEDVDzNLk8gn4c03acnT89NwB44xQmhqFUlc3QjX7w/kjO9jZxqtifIkuo9FqTJkfSs87BGJ/lu4EZnxyn89L1lanGsGyJlAO/rB1l1kBfCmbpmOTEhhRqohaSINUzPDdepwExLbKZSkjQ4jP8cXdO59/W3WP+iI5mLbTzidBcAi4EcYIsqkjt/KqMC/7HX6FN9Ji1j30JVskV/QDZMl3FGq/M5Igl6jkDTMYuRJAj1+e9UzyJL5ehr71OdbmEINyuubMNMrKFAWLSfI+ZMeLGAfqZ2n/6jHryeOFkN/Rb7/H1DxdbqJNC156bH+7xxh8RdTvT+3KKZ20oXwZ4BWwdmezA+zHBTWDXRqmZoPRwMKGUs4gWFtCm7P4ezBZXTs9zFHLh5CGhv5RmqaI/Yl71T0FXohj22MGuDR/DzKj2Y/zsL9hGxh7FdIc7v4GieLhUdrOzKHDay+l0AgLjZAVxctvtLWiBn6eefgyfj1bd7ZgaH//NAc1gwjI0y+mpfxw2axesOf0HevcA7cL2JQeFEb/aDWK4THikDX5S1o25cOVuR2GU81tig+P0CMA/8n/WO+yz4NGUDmpuzZoAkFD1z3lGPih9v5wtKlQFpiaGLknGrFJ00MLRkgZJsBwuigM9QF0YfeLRfYH94yA5IpwAivZX6t8pxXcoNaZTpN4X6nR90SCFj7QyLNmxoKeF90QgQiKheNBU5gxJqlY20e4TIbRpDvSsl49ASzFVQrUZ2k7uh6F+D1X/8ptXCDBI8RMObYr3ecbj2Kkao8q6beD6tgX/MzgDSoleFuJa3SnkLv9Rb7iHqUDMz/1AEXVo8flIAxuVcpDbB62dlPmcPLT6Y4cHdTv53aRNoiBvnIvrHT/AWyWqTYMGySS6KSO2mscl6+/JBWRHilRGcTmJBYLrQxVGAagyKTTcOzZVtWx2EZgeR0RMwrFcaOl9FPO6OaTfRXxKOTtBjJgXet7Od9EroB4GfZOhTBt3KPUW/E1PSVKiD4JSWe+sCfhaLhXa2uwwFGNmJO0TB
  template:
    metadata:
      name: postgresql-credentials
      namespace: carte-fede-codex-frontend-backend-http-routes
