---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carte-fede-backend-credentials
  namespace: carte-fede-main
spec:
  encryptedData:
    SECRET_KEY: AgCNeAYyegH2pQ0+jL8cODo0RNLcHH167fInEpXwvTC0/FaMjD6sFVdFG+kvY2JxIDGn3xKfYjnJeAMdPgUE2PZ+y+78IKIBofTkUDGf1OzXgsmTGl2PhsWasQjtYeTwoD2CjMLa3S1Y0bSyJp6Q3W8psyssH3SWZZKBV6jfZy7Uu1c3xGnL6OxF8JewQRVc1w/V6FYVupbs9+bngMQuEuX2JoFVKY09uL6s54Ccwd5wqR38IxRJpPfS67ERxpy4NSSCHUIyqmVMDJc2EmFITTq1+TXq4H0wi9V1+eF9rVQyKwzHol+jqomwEnkjmojWSAerZJmrWrU/dBPEH502V5na7corIlaxUiwhaRFO63XZ4NpCSa5fL4BneeTknX4IiLAes3YMDgVixs+UdwO3+tvrW/sJH4XcITepJEdFb752tm/xsyWkqeUgCeHI4bAGCpNZT8bljEUbPoFgJ6vMd4LAE3nA5A3TKGjnL2ZiVt+tAgIzWAid5xlEWTaS6mlq0se1NXizQjMT8eKE4XgnYo4qlYsbOpdS+bgKPOPUpRld84lDH5Cf8n5+UevRfkTGd5NaBuw4PfnerX9Z9xaiIttRxxEhxJMizcLgHJSMaFD1TL5s3exI3wLhxSqXnBeuZWAt+cwz6KSSvSIdIZyFYLZcEWekREZvQURT1AwSN1YrACjVT8kbt20Nq+JKBteI/1UasK50kg0=
  template:
    metadata:
      name: carte-fede-backend-credentials
      namespace: carte-fede-main
    type: Opaque
