---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carte-fede-backend-credentials
  namespace: carte-fede-main
spec:
  encryptedData:
    SECRET_KEY: AgCR/J9u9Us9d1sNh/+a50CV9esqt9/yus1idensuRuz6XVNL3nc0EtvO5E1Do3tQuJ5LX69Jy/e0wzTaoxO6SnPGz5Nm+erWO2UL8uMG9zZf4Psk49X13FlbrhV3HGxk8G7OF6aC5eJqPTsTsBvf2V5AbdGlZPUQpgjZRdSYr85B8smSCuWttJQgf8N952V04ZxmciW+T/ZL7iMGHeVtrfCoEVQHdOF+qPcisRWfljZK34Z6TcmrNbCfJ1hNCmRIBLc7GgeH7ENHiudMIOAu2QDAvph94xjMX+2p9vSPYnUrXy6zD3yfjdBq36ludIp1QTPZQJha5Wed1A+IOXmIwmUrYR95rvBhIdsFLxEXMPo8Rsg5bRfminGdk7vmiuFrxMrgoAmzDmhdztQL1fi+kIfHnJuX+7IvF68DNgl6MhwkG4HFJXg7OJSL6fJzXdARV0Gk0FddsYK33cOFpz/v7PZZzPzwIe86L/7SyMHhORrzbTkL3fC8KC1Uv1GJXefpYPK+0OTIQoW81aw/vo3Z0q54ZL0/uYfuIKNp/aujLAyEiNLMNOafpVnHtmKy3KR2iMRwael0AYW5bxxxGqWARAsOTVaT3bpDdRomI5uA6iEZaqXW/PRFYZzcfwH58uVyNmjdX1gYV6OhAFatrIIb/bdzVXiUHRCz182jFxmM3g4PpcXccy4xKSPyhN2XDWsjNHYpoCCFPAxReZPqpIssO+ozToUPnwKTxw33YFbYup/2i9AVjh3/SDN6q9CTNK+jTDRg8vxuZc0/gW/tIcDuYAn
  template:
    metadata:
      name: carte-fede-backend-credentials
      namespace: carte-fede-main
    type: Opaque
